### PR TITLE
fix: talkback stream bitrate settings

### PR DESCRIPTION
**Pull request by cryptk**
### Description of change

Adjust the ffmpeg command for the TalkbackStream, specifically the bitrate and sampling rate settings, to correct them to values that give proper audio from the camera speaker.  I only have a couple of G4 Instant cameras to test with, but this change results in almost perfect audio coming from them.

There is still considerable popping in the audio, but at least now it doesn't sound muddled, and it plays at the correct speed.  I'll continue playing with ffmpeg to see if I can get a nice clean stream to one of my cameras and send in another PR to further increase the audio quality if I figure anything else out, but as-is, this PR is a big step in a good direction, it's actually usable now with TTS whereas before it was so fast and muddled you could barely understand what was being said.

### Pull-Request Checklist

- [x] Code is up-to-date with the `main` branch
- [x] This pull request follows the [contributing guidelines](https://github.com/uilibs/uiprotect/blob/main/CONTRIBUTING.md).
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/), such as "fix(api): prevent racing of requests".

> - If pre-commit.ci is failing, try `pre-commit run -a` for further information.
> - If CI / test is failing, try `poetry run pytest` for further information.

## Summary by CodeRabbit

- **New Features**
	- Streamlined command construction for audio bitrate and UDP bitrate by directly utilizing the sampling rate from talkback settings.
  
- **Bug Fixes**
	- Removed unnecessary calculations for bitrate, improving efficiency in command string generation.

### CODE REVIEW

**Comment by bdraco** [comment]
This looks like a reasonable change to me.  I'd like someone with a doorbell to test it before merging

**Comment by cryptk** [comment]
@bdraco my G4 Doorbell Pro arrives on Tuesday, I'll test it then and report back. I actually discovered the issue because I was setting up the automations that I want to use with the doorbell when it arrives and discovered the poor audio quality.

**Comment by joenye** [comment]
I'm curious if you're able to play anything out of the doorbell. I have some G5 Domes and I can reproduce the same broken audio behaviour. But my G4 Doorbell Pro PoE doesn't making any sound at all when I play to it.

**Comment by cryptk** [comment]
@bdraco just tested and this fix greatly improves audio for the G4 Doorbell Pro as well.  Change in quality was the same as for the G4 Instant.  The audio is now playing at the correct speed, much less muddled, but there is still some audio popping that happens.

I know that Home Assistant is working on their November release, what are the chances that this fix can make it in for that?

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
@cryptk https://github.com/uilibs/uiprotect/releases/tag/v6.3.2 released. Please open a PR to Home Assistant to bump the library. I can approve it today before I go to the airport if you do it in the next hour

**Comment by TheJulianJES** [comment]
This goes for either of you, but if you ever need a uiprotect PR reviewed in HA, just ping me there. 😄

**Pull request merged**
