### PR TITLE
refactor: reduce duplicate code to process sensor events

### PR DESCRIPTION
**Pull request by bdraco**
### Description of change

reduce duplicate code to process sensor events

### CODE REVIEW

**Comment by bdraco** [comment]
@coderabbitai review

**Comment by bdraco** [comment]
This one could use another set of 👀 before merging since sensors currently have no test cover

**Review by TheJulianJES — APPROVED** [review]
I don’t see anything wrong 😄

**Comment by bdraco** [comment]
thanks.

I'll do _process_camera_event in a followup

**Pull request merged**
